apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: hytaty/spring-petclinic-admin-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: SPRING_BOOT_ADMIN_DISCOVERY_ENABLED
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090