apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: hytaty/spring-petclinic-discovery-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
          
---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
  