apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: springcommunity/spring-petclinic-genai-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
---

apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  selector:
    app: genai-service
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
