apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      org_id: 1
      url: http://prometheus-server:9090
      is_default: true
      version: 1
      editable: true
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      is_default: false
      editable: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana-server
        image: grafana/grafana
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-server
spec:
  selector:
    app: grafana-server
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
