apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: hytaty/spring-petclinic-vets-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8083
          env:
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"


---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083