apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
    rule_files:
      - /etc/prometheus/rules/prometheus-rules.yml
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ['localhost:9090']
    - job_name: api-gateway
      metrics_path: /actuator/prometheus
      static_configs:
      - targets: ['api-gateway.default.svc.cluster.local:80']
    - job_name: customers-service
      metrics_path: /actuator/prometheus
      static_configs:
      - targets: ['customers-service.default.svc.cluster.local:80']
    - job_name: visits-service
      metrics_path: /actuator/prometheus
      static_configs:
      - targets: ['visits-service.default.svc.cluster.local:80']
    - job_name: vets-service
      metrics_path: /actuator/prometheus
      static_configs:
      - targets: ['vets-service.default.svc.cluster.local:80']
    - job_name: genai-service
      metrics_path: /actuator/prometheus
      static_configs:
      - targets: ['genai-service.default.svc.cluster.local:80']
  prometheus-rules.yml: |
    groups:
    - name: petclinic-rules
      rules:
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{job=~"api-gateway|customers-service|visits-service|vets-service|genai-service", status=~"5.."}[30s])) > 10
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected on PetClinic"
          description: "The number of 5xx errors exceeds 10 in 30 seconds for service {{ $labels.service }}."