groups:
- name: error_alert
  rules:
  - alert: HighErrorRate
    expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[30s])) > 10
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "High error rate"