groups:
- name: petclinic-rules
  rules:
  - alert: HighErrorRate
    expr: sum(rate(http_server_requests_seconds_count{job=~"api-gateway|customers-service|visits-service|vets-service|genai-service", status=~"5.."}[30s])) > 10
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected on PetClinic"
      description: "The number of 5xx errors exceeds 10 in 30 seconds for service {{ $labels.service }}."