server:
  http_listen_port: 9080
  grpc_listen_port: 0

client:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/position.yaml

scrape_configs:
  - job_name: kubernetes-pods
    pineline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__:/var/logs/container/*.log
